name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Container Registry に認証
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker ビルド
        run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Docker イメージをプッシュ
        run: docker push ghcr.io/${{ github.repository }}:latest
